
workspace = 1, monitor:desc:Lenovo Group Limited L27qe UTP02HZK, default:true
workspace = 2, monitor:desc:Lenovo Group Limited L27qe UTP02HZK
workspace = 3, monitor:desc:Lenovo Group Limited L27qe UTP02HZK
workspace = 4, monitor:desc:Lenovo Group Limited L27qe UTP02HZK
workspace = 5, monitor:desc:Lenovo Group Limited L27qe UTP02HZK

workspace = 6, monitor:desc:Lenovo Group Limited L27qe UTP02HZR, default:true
workspace = 7, monitor:desc:Lenovo Group Limited L27qe UTP02HZR
workspace = 8, monitor:desc:Lenovo Group Limited L27qe UTP02HZR
workspace = 9, monitor:desc:Lenovo Group Limited L27qe UTP02HZR

workspace = 10, monitor:desc:BOE 0x0AE0, default:true
