
workspace = 1, monitor:desc:Dell Inc. DELL U2719D 9JWNY13, default:true
workspace = 2, monitor:desc:Dell Inc. DELL U2719D 9JWNY13
workspace = 3, monitor:desc:Dell Inc. DELL U2719D 9JWNY13
workspace = 4, monitor:desc:Dell Inc. DELL U2719D 9JWNY13
workspace = 5, monitor:desc:Dell Inc. DELL U2719D 9JWNY13

workspace = 6, monitor:desc:Dell Inc. DELL U2719D 1JWNY13, default:true
workspace = 7, monitor:desc:Dell Inc. DELL U2719D 1JWNY13
workspace = 8, monitor:desc:Dell Inc. DELL U2719D 1JWNY13
workspace = 9, monitor:desc:Dell Inc. DELL U2719D 1JWNY13

workspace = 10, monitor:desc:BOE 0x0AE0, default:true
