
workspace = 1, monitor:desc:Philips Consumer Electronics Company PHL 275E2F UHB2050003236, default:true
workspace = 2, monitor:desc:Philips Consumer Electronics Company PHL 275E2F UHB2050003236
workspace = 3, monitor:desc:Philips Consumer Electronics Company PHL 275E2F UHB2050003236
workspace = 4, monitor:desc:Philips Consumer Electronics Company PHL 275E2F UHB2050003236
workspace = 5, monitor:desc:Philips Consumer Electronics Company PHL 275E2F UHB2050003236

workspace = 6, monitor:desc:HP Inc. HP E27q G4 CNK1191FZX, default:true
workspace = 7, monitor:desc:HP Inc. HP E27q G4 CNK1191FZX
workspace = 8, monitor:desc:HP Inc. HP E27q G4 CNK1191FZX
workspace = 9, monitor:desc:HP Inc. HP E27q G4 CNK1191FZX

workspace = 10, monitor:desc:BOE 0x0AE0, default:true
