#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff0c1014
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          1
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   2

# set transparency
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# Only manage the main windows of Emacs, not child-frames
yabai -m rule --add label=emacs title="Emacs v.*" app=Emacs manage=on

# Override floating mode for..
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" title="Copy" manage=off
yabai -m rule --add app="^python$" title="Score" manage=off

yabai -m rule --add label=ignoreTeamsNotification app="Microsoft Teams" title="Microsoft Teams Notification" manage=off

yabai -m signal --add \
      event=application_activated \
      app="^Microsoft Teams$" \
      action='${HOME}/.config/yabai/scripts/defeat-teams'

yabai -m signal --add \
      event=window_focused \
      app="^Microsoft Teams$" \
      title="^Microsoft Teams Notification$" \
      action='${HOME}/.config/yabai/scripts/defeat-teams'

# Only manage the main window of Gimp
yabai -m rule --add label=gimpPopups app="^Gimp.*" title!="( - Gimp$|^GNU Image Manipulation Program)" manage=off


echo "yabai configuration loaded.."
